/* Auto-generated NFC data — do not edit manually */

const G="https://fdn2.gsmarena.com/vv/pics/";
function gi(b,s,i){return G+b+"/"+s+"-"+(i||1)+".jpg";}
const ANT=[{s:"#DC2626",bg:"rgba(220,38,38,.16)"},{s:"#00A878",bg:"rgba(0,168,120,.2)"},{s:"#EAB308",bg:"rgba(234,179,8,.2)"}];
const SC={excellent:{b:"sb-ex",p:"background:#E0F5EF;color:#085041",l:"Excellent"},ok:{b:"sb-ok",p:"background:#E6EEFF;color:#003DB3",l:"Bon"},ko:{b:"sb-ko",p:"background:#FEF3C7;color:#633806",l:"Moyen"},bad:{b:"sb-bad",p:"background:#FEE2E2;color:#7F1D1D",l:"Mauvais"}};
function sc(k){return SC[k]||SC.ok;}

const OV={
  /* Positions relative to the clipped BACK view (215×420px clip window) */
  /* top_edge = iPhone tranche supérieure */
  top_edge:  {t:'0%',  l:'5%',  w:'90%', h:'7%'},
  /* top_back = Samsung S26U NFC 1 — haut dos, sous barre caméra */
  top_back:  {t:'12%', l:'8%',  w:'84%', h:'30%'},
  /* top_back2 = position standard haut dos (S24U, Pixel, etc.) */
  top_back2: {t:'18%', l:'8%',  w:'84%', h:'28%'},
  /* mid_back = S23U (co-localisée bobine) — centre exact */
  mid_back:  {t:'38%', l:'8%',  w:'84%', h:'27%'},
  /* low_back = S25U — tiers inférieur */
  low_back:  {t:'52%', l:'8%',  w:'84%', h:'27%'},
  /* top_strip = S26U NFC 2 — tranche supérieure (fine bande) */
  top_strip: {t:'0%',  l:'5%',  w:'90%', h:'6%'},
};

const DB={

apple:{label:'Apple',models:{
  'ip17-pm':{label:'iPhone 17 Pro Max',year:2025,img:gi('apple','apple-iphone-17-pro-max'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'77.6×163.0mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip17-pro':{label:'iPhone 17 Pro',year:2025,img:gi('apple','apple-iphone-17-pro'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×149.6mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip17-air':{label:'iPhone Air',year:2025,img:gi('apple','apple-iphone-air'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×163.0mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip17':{label:'iPhone 17',year:2025,img:gi('apple','apple-iphone-17'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×147.6mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip17e':{label:'iPhone 17e',year:2025,img:gi('apple','apple-iphone-17e'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×138.8mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~62×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip16e':{label:'iPhone 16e',year:2025,img:gi('apple','apple-iphone-16e'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×138.8mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~62×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip16-pm':{label:'iPhone 16 Pro Max',year:2024,img:gi('apple','apple-iphone-16-pro-max'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'77.6×163.0mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip16-pro':{label:'iPhone 16 Pro',year:2024,img:gi('apple','apple-iphone-16-pro'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×149.6mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip16-plus':{label:'iPhone 16 Plus',year:2024,img:gi('apple','apple-iphone-16-plus'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'77.8×160.9mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip16':{label:'iPhone 16',year:2024,img:gi('apple','apple-iphone-16'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×147.6mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip15-pm':{label:'iPhone 15 Pro Max',year:2023,img:gi('apple','apple-iphone-15-pro-max'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'76.7×159.9mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip15-pro':{label:'iPhone 15 Pro',year:2023,img:gi('apple','apple-iphone-15-pro'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×146.6mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip15-plus':{label:'iPhone 15 Plus',year:2023,img:gi('apple','apple-iphone-15-plus'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'77.8×160.9mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip15':{label:'iPhone 15',year:2023,img:gi('apple','apple-iphone-15'),crop:'L',chip:'Apple NFC+UWB',score:'excellent',zones:1,range:'3–5 cm',dims:'71.6×147.6mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip14-pm':{label:'iPhone 14 Pro Max',year:2022,img:gi('apple','apple-iphone-14-pro-max'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'77.6×160.7mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip14-pro':{label:'iPhone 14 Pro',year:2022,img:gi('apple','apple-iphone-14-pro'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×147.5mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip14-plus':{label:'iPhone 14 Plus',year:2022,img:gi('apple','apple-iphone-14-plus'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'77.8×160.9mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip14':{label:'iPhone 14',year:2022,img:gi('apple','apple-iphone-14'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×146.7mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip13-pm':{label:'iPhone 13 Pro Max',year:2021,img:gi('apple','apple-iphone-13-pro-max'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'78.1×160.8mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Cryptnox',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip13-pro':{label:'iPhone 13 Pro',year:2021,img:gi('apple','apple-iphone-13-pro'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×146.7mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Cryptnox',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip13-mini':{label:'iPhone 13 Mini',year:2021,img:gi('apple','apple-iphone-13-mini'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'64.2×131.5mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~55×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip13':{label:'iPhone 13',year:2021,img:gi('apple','apple-iphone-13'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×146.7mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Cryptnox',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip12-pm':{label:'iPhone 12 Pro Max',year:2020,img:gi('apple','apple-iphone-12-pro-max'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'78.1×160.8mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~70×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip12-pro':{label:'iPhone 12 Pro',year:2020,img:gi('apple','apple-iphone-12-pro'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×146.7mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip12-mini':{label:'iPhone 12 Mini',year:2020,img:gi('apple','apple-iphone-12-mini'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'64.2×131.5mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~55×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip12':{label:'iPhone 12',year:2020,img:gi('apple','apple-iphone-12'),crop:'L',chip:'Apple NFC',score:'excellent',zones:1,range:'3–5 cm',dims:'71.5×146.7mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~65×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip11-pm':{label:'iPhone 11 Pro Max',year:2019,img:gi('apple','apple-iphone-11-pro-max'),crop:'L',chip:'Apple NFC',score:'ok',zones:1,range:'3–5 cm',dims:'77.8×158.0mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~68×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip11-pro':{label:'iPhone 11 Pro',year:2019,img:gi('apple','apple-iphone-11-pro'),crop:'L',chip:'Apple NFC',score:'ok',zones:1,range:'3–5 cm',dims:'71.4×144.0mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~62×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip11':{label:'iPhone 11',year:2019,img:gi('apple','apple-iphone-11'),crop:'L',chip:'Apple NFC',score:'ok',zones:1,range:'3–5 cm',dims:'75.7×150.9mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~66×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip-xs-max':{label:'iPhone XS Max',year:2018,img:gi('apple','apple-iphone-xs-max'),crop:'L',chip:'Apple NFC',score:'ok',zones:1,range:'3–5 cm',dims:'77.4×157.5mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~68×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip-xs':{label:'iPhone XS',year:2018,img:gi('apple','apple-iphone-xs'),crop:'L',chip:'Apple NFC',score:'ok',zones:1,range:'3–5 cm',dims:'70.9×143.6mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~60×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
  'ip-se-2020':{label:'iPhone SE (2020)',year:2020,img:gi('apple','apple-iphone-se-2020'),crop:'L',chip:'Apple NFC',score:'ok',zones:1,range:'3–5 cm',dims:'67.3×138.4mm',ants:[{id:1,lbl:'Antenne tranche sup.',pos:'Tranche supérieure',size:'~60×4mm',conf:'confirmed',src:'Apple Dev Docs',ov:OV.top_edge}],tap:'<b>Tranche supérieure</b>.',tapCls:'tb-ok',crop:'L'},
}},

/* ── GOOGLE ── */

asus:{label:'Asus',models:{
  'rog8-pro':{label:'ROG Phone 8 Pro',year:2024,img:gi('asus','asus-rog-phone-8-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'77.0×163.8mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'zenfone11':{label:'Zenfone 11 Ultra',year:2024,img:gi('asus','asus-zenfone-11-ultra'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'77.0×163.8mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'rog7':{label:'ROG Phone 7',year:2023,img:gi('asus','asus-rog-phone-7'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'77.0×173.0mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'zenfone10':{label:'Zenfone 10',year:2023,img:gi('asus','asus-zenfone-10'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'68.1×146.5mm',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~50×38mm',conf:'estimated',src:'Observations',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── NOKIA ── */

blackview:{label:'Blackview',models:{
  'bl9000-pro':{label:'BL9000 Pro',year:2024,img:gi('blackview','blackview-bl9000-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'80.0×173.0mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'bv9800pro':{label:'BV9800 Pro',year:2020,img:gi('blackview','blackview-bv9800-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'83.7×168.3mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── DOOGEE ── */

doogee:{label:'Doogee',models:{
  's110':{label:'S110',year:2024,img:gi('doogee','doogee-s110'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'86.5×169.3mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  's98pro':{label:'S98 Pro',year:2022,img:gi('doogee','doogee-s98-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'82.0×170.5mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── ULEFONE ── */

fairphone:{label:'Fairphone',models:{
  'fp5':{label:'Fairphone 5',year:2023,img:gi('fairphone','fairphone-5'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'75.8×161.9mm',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55×40mm',conf:'estimated',src:'Fairphone Support',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'fp4':{label:'Fairphone 4',year:2021,img:gi('fairphone','fairphone-4'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'75.4×158.9mm',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55×40mm',conf:'estimated',src:'Fairphone Support',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── TCL ── */

google:{label:'Google',models:{
  'p10a':{label:'Pixel 10a',year:2025,img:gi('google','google-pixel-10a'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p10-pf':{label:'Pixel 10 Pro Fold',year:2025,img:gi('google','google-pixel-10-pro-fold--'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p10-pxl':{label:'Pixel 10 Pro XL',year:2025,img:gi('google','google-pixel-10-pro-xl-'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p10-pro':{label:'Pixel 10 Pro',year:2025,img:gi('google','google-pixel-10-pro-'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p10':{label:'Pixel 10',year:2025,img:gi('google','google-pixel-10-'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p9a':{label:'Pixel 9a',year:2025,img:gi('google','google-pixel-9a'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p9-pxl':{label:'Pixel 9 Pro XL',year:2024,img:gi('google','google-pixel-9-pro-xl-'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p9-pro':{label:'Pixel 9 Pro',year:2024,img:gi('google','google-pixel-9-pro-'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p9-fold':{label:'Pixel 9 Pro Fold',year:2024,img:gi('google','google-pixel-9-pro-fold-'),crop:'L',chip:'NXP (probable)',score:'ko',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos (plié)',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.mid_back}],tap:'Pliable — <b>tiers supérieur du dos</b>.',tapCls:'tb-warn',crop:'L'},
  'p9':{label:'Pixel 9',year:2024,img:gi('google','google-pixel-9-'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p8a':{label:'Pixel 8a',year:2024,img:gi('google','google-pixel-8a'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p8-pro':{label:'Pixel 8 Pro',year:2023,img:gi('google','google-pixel-8-pro'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p8':{label:'Pixel 8',year:2023,img:gi('google','google-pixel-8'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p-fold':{label:'Pixel Fold',year:2023,img:gi('google','google-pixel-fold'),crop:'L',chip:'NXP (probable)',score:'ko',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos (plié)',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.mid_back}],tap:'Pliable — <b>tiers supérieur du dos</b>.',tapCls:'tb-warn',crop:'L'},
  'p7a':{label:'Pixel 7a',year:2023,img:gi('google','google-pixel-7a'),crop:'L',chip:'NXP (probable)',score:'excellent',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p7-pro':{label:'Pixel 7 Pro',year:2022,img:gi('google','google-pixel7-pro-new'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p7':{label:'Pixel 7',year:2022,img:gi('google','google-pixel7-new'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p6a':{label:'Pixel 6a',year:2022,img:gi('google','google-pixel-6a'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p6-pro':{label:'Pixel 6 Pro',year:2021,img:gi('google','google-pixel-6-pro'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p6':{label:'Pixel 6',year:2021,img:gi('google','google-pixel-6'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p5a':{label:'Pixel 5a 5G',year:2021,img:gi('google','google-pixel-5a-5g'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p5':{label:'Pixel 5',year:2020,img:gi('google','google-pixel-5-5g'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p4a5g':{label:'Pixel 4a 5G',year:2020,img:gi('google','google-pixel-4a-5g'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p4a':{label:'Pixel 4a',year:2020,img:gi('google','google-pixel-4a'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p4xl':{label:'Pixel 4 XL',year:2019,img:gi('google','google-pixel-4-r1'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p4':{label:'Pixel 4',year:2019,img:gi('google','google-pixel-4-r1'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p3axl':{label:'Pixel 3a XL',year:2019,img:gi('google','google-pixel-3a-xl-'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p3a':{label:'Pixel 3a',year:2019,img:gi('google','google-pixel-3a'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p3xl':{label:'Pixel 3 XL',year:2018,img:gi('google','google-pixel-3xl-'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p3':{label:'Pixel 3',year:2018,img:gi('google','google-pixel-3-'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p2xl':{label:'Pixel 2 XL',year:2017,img:gi('google','google-pixel-xl2-'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
  'p2':{label:'Pixel 2',year:2017,img:gi('google','google-pixel-2'),crop:'L',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Cryptnox · GadgetGuideOnline',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'L'},
}},
/* ── ONEPLUS ── */

honor:{label:'Honor',models:{
  'magic7-pro':{label:'Magic7 Pro',year:2025,img:gi('honor','honor-magic7-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'75.3×162.0mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'magic6-pro':{label:'Magic6 Pro',year:2024,img:gi('honor','honor-magic6-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'75.9×163.4mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'magic-v3':{label:'Magic V3',year:2024,img:gi('honor','honor-magic-v3',3),chip:'NXP (probable)',score:'ko',zones:1,range:'2–4 cm',dims:'74.0×160.0mm plié',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos (plié)',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'Pliable — <b>tiers supérieur du dos</b>.',tapCls:'tb-warn',crop:'C'},
  'magic5-pro':{label:'Magic5 Pro',year:2023,img:gi('honor','honor-magic5-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'74.9×162.9mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'x9b':{label:'X9b',year:2024,img:gi('honor','honor-x9b'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'74.9×163.0mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── HUAWEI ── */

huawei:{label:'Huawei',models:{
  'pura70-ultra':{label:'Pura 70 Ultra',year:2024,img:gi('huawei','huawei-pura-70-ultra'),crop:'C',chip:'Interne Huawei',score:'ok',zones:1,range:'3–5 cm',dims:'75.1×163.4mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'mate60-pro':{label:'Mate 60 Pro',year:2023,img:gi('huawei','huawei-mate-60-pro'),crop:'C',chip:'Interne Huawei',score:'ok',zones:1,range:'3–5 cm',dims:'75.5×162.5mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'p60-pro':{label:'P60 Pro',year:2023,img:gi('huawei','huawei-p60-pro'),crop:'C',chip:'Interne Huawei',score:'ok',zones:1,range:'3–5 cm',dims:'74.5×161.1mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── REALME ── */

infinix:{label:'Infinix',models:{
  'hot40-pro':{label:'Hot 40 Pro',year:2024,img:gi('infinix','infinix-hot-40-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.3×167.2mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'note30-pro':{label:'Note 30 Pro',year:2023,img:gi('infinix','infinix-note-30-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.5×167.2mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── BLACKVIEW ── */

motorola:{label:'Motorola',models:{
  'razr60-ultra':{label:'Razr 60 Ultra',year:2025,img:gi('motorola','motorola-razr-60-ultra',3),chip:'NXP (probable)',score:'ko',zones:1,range:'2–4 cm',dims:'73.9×170.8mm déplié',ants:[{id:1,lbl:'Antenne dos',pos:'Panneau sup. (plié)',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'Pliable — <b>panneau supérieur du dos</b>.',tapCls:'tb-warn',crop:'C'},
  'edge50-ultra':{label:'Edge 50 Ultra',year:2024,img:gi('motorola','motorola-edge-50-ultra'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'72.5×161.7mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'edge50-pro':{label:'Edge 50 Pro',year:2024,img:gi('motorola','motorola-edge-50-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'72.5×161.7mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'edge40-pro':{label:'Edge 40 Pro',year:2023,img:gi('motorola','motorola-edge-40-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'73.3×161.2mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'thinkphone':{label:'ThinkPhone',year:2023,img:gi('motorola','motorola-thinkphone'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'73.3×158.8mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── OPPO ── */

nokia:{label:'Nokia',models:{
  'xr21':{label:'XR21',year:2023,img:gi('nokia','nokia-xr21'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'77.6×167.0mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'x30':{label:'X30 5G',year:2022,img:gi('nokia','nokia-x30-5g'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'73.9×158.8mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'g60':{label:'G60 5G',year:2022,img:gi('nokia','nokia-g60-5g'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'74.3×166.7mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── FAIRPHONE ── */

nothing:{label:'Nothing',models:{
  'phone-3a':{label:'Phone (3a)',year:2025,img:gi('nothing','nothing-phone-3a'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.7×162.1mm',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'phone-2a':{label:'Phone (2a)',year:2024,img:gi('nothing','nothing-phone-2a'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.4×162.1mm',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'phone-2':{label:'Phone (2)',year:2023,img:gi('nothing','nothing-phone-2'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.4×162.1mm',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'phone-1':{label:'Phone (1)',year:2022,img:gi('nothing','nothing-phone-1'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'75.8×159.2mm',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── ASUS ── */

oneplus:{label:'OnePlus',models:{
  'op13':{label:'OnePlus 13',year:2025,img:gi('oneplus','oneplus-13'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.0×162.6mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'op12':{label:'OnePlus 12',year:2024,img:gi('oneplus','oneplus-12'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'75.8×164.3mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'op12r':{label:'OnePlus 12R',year:2024,img:gi('oneplus','oneplus-12r'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'74.5×163.3mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'op-open':{label:'OnePlus Open',year:2023,img:gi('oneplus','oneplus-open',3),chip:'NXP (probable)',score:'ko',zones:1,range:'2–4 cm',dims:'73.3×153.4mm plié',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-warn',crop:'C'},
  'op11':{label:'OnePlus 11',year:2023,img:gi('oneplus','oneplus-11'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'74.1×163.1mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'nord3':{label:'Nord 3 5G',year:2023,img:gi('oneplus','oneplus-nord-3-5g'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'73.3×161.3mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── XIAOMI ── */

oppo:{label:'Oppo',models:{
  'find-n5':{label:'Find N5',year:2025,img:gi('oppo','oppo-find-n5',3),chip:'NXP (probable)',score:'ko',zones:1,range:'2–4 cm',dims:'68.6×156.0mm plié',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos (plié)',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'Pliable — <b>tiers supérieur du dos</b>.',tapCls:'tb-warn',crop:'C'},
  'find-x8-pro':{label:'Find X8 Pro',year:2025,img:gi('oppo','oppo-find-x8-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.0×162.4mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'find-x8':{label:'Find X8',year:2025,img:gi('oppo','oppo-find-x8'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'74.5×161.3mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'find-x6-pro':{label:'Find X6 Pro',year:2023,img:gi('oppo','oppo-find-x6-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'75.7×163.6mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'reno12-pro':{label:'Reno12 Pro',year:2024,img:gi('oppo','oppo-reno12-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'74.3×161.5mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── VIVO ── */

realme:{label:'Realme',models:{
  'gt7-pro':{label:'GT7 Pro',year:2024,img:gi('realme','realme-gt-7-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.0×161.5mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'gt6':{label:'GT6',year:2024,img:gi('realme','realme-gt-6'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'76.0×161.5mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'gt5-pro':{label:'GT5 Pro',year:2024,img:gi('realme','realme-gt-5-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'74.9×162.3mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
  'gt2-pro':{label:'GT2 Pro',year:2022,img:gi('realme','realme-gt-2-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3–5 cm',dims:'73.9×163.2mm',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55×40mm',conf:'estimated',src:'Observations',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'C'},
}},

/* ── NOTHING ── */

/* -- SAMSUNG -- */
samsung:{label:'Samsung',models:{
  's26-ultra':{label:'S26 Ultra',year:2026,rec:true,img:gi('samsung','samsung-galaxy-s26-ultra'),crop:'R',chip:'NXP SN300U',score:'excellent',zones:2,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~58x44mm',conf:'confirmed',src:'Samsung HK',ov:OV.top_back,crop:'R'},{id:2,lbl:'Antenne tranche',pos:'Tranche sup.',size:'~68x5mm',conf:'confirmed',src:'SamMobile 2026',ov:OV.top_strip}],tap:'<b>Haut dos</b> (rouge) OU <b>tranche sup.</b> (vert).',tapCls:'tb-ok'},
  's26-plus':{label:'S26+',year:2026,img:gi('samsung','samsung-galaxy-s26-plus'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's26':{label:'S26',year:2026,img:gi('samsung','samsung-galaxy-s26'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's25-fe':{label:'S25 FE',year:2025,img:gi('samsung','samsung-galaxy-s25-fe'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's25-edge':{label:'S25 Edge',year:2025,img:gi('samsung','samsung-galaxy-s25-edge'),crop:'R',chip:'NXP SN300U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers inférieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.low_back}],tap:'<b>Tiers inférieur du dos</b> — contre-intuitif.',tapCls:'tb-warn',crop:'R'},
  'z-fold7':{label:'Z Fold7',year:2025,img:gi('samsung','samsung-galaxy-z-fold7'),crop:'R',chip:'NXP SN300U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'z-flip7':{label:'Z Flip7',year:2025,img:gi('samsung','samsung-galaxy-z-flip7'),crop:'R',chip:'NXP SN300U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'z-trifold':{label:'Z TriFold',year:2025,img:gi('samsung','samsung-galaxy-z-trifold-'),crop:'R',chip:'NXP SN300U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'a57':{label:'Galaxy A57',year:2025,img:gi('samsung','samsung-galaxy-a57'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a37':{label:'Galaxy A37',year:2025,img:gi('samsung','samsung-galaxy-a37'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a56':{label:'Galaxy A56',year:2025,img:gi('samsung','samsung-galaxy-a56-'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a36':{label:'Galaxy A36',year:2025,img:gi('samsung','samsung-galaxy-a36'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a26':{label:'Galaxy A26',year:2025,img:gi('samsung','samsung-galaxy-a26'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's25-ultra':{label:'S25 Ultra',year:2025,img:gi('samsung','samsung-galaxy-s25-ultra-sm-s938'),crop:'R',chip:'NXP SN300U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers inférieur dos',size:'~55x40mm',conf:'confirmed',src:'Samsung HK NFC',ov:OV.low_back}],tap:'<b>Tiers inférieur du dos</b> — contre-intuitif.',tapCls:'tb-warn',crop:'R'},
  's25-plus':{label:'S25+',year:2025,img:gi('samsung','samsung-galaxy-s25-plus-sm-s936'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's25':{label:'S25',year:2025,img:gi('samsung','samsung-galaxy-s25-sm-s931'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's24-ultra':{label:'S24 Ultra',year:2024,img:gi('samsung','samsung-galaxy-s24-ultra'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'confirmed',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's24-plus':{label:'S24+',year:2024,img:gi('samsung','samsung-galaxy-s24-plus'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's24':{label:'S24',year:2024,img:gi('samsung','samsung-galaxy-s24'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'confirmed',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's24-fe':{label:'S24 FE',year:2024,img:gi('samsung','samsung-galaxy-s24-fe'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'z-fold6':{label:'Z Fold6',year:2024,img:gi('samsung','samsung-galaxy-z-fold6'),crop:'R',chip:'NXP SN300U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'z-flip6':{label:'Z Flip6',year:2024,img:gi('samsung','samsung-galaxy-z-flip6'),crop:'R',chip:'NXP SN300U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'a55':{label:'Galaxy A55',year:2024,img:gi('samsung','samsung-galaxy-a55'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a35':{label:'Galaxy A35',year:2024,img:gi('samsung','samsung-galaxy-a35'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'xcover7':{label:'Xcover7',year:2024,img:gi('samsung','samsung-galaxy-xcover7-sm-g556b'),crop:'R',chip:'NXP SN300U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's23-ultra':{label:'S23 Ultra',year:2023,img:gi('samsung','samsung-galaxy-s23-ultra-5g'),crop:'R',chip:'NXP SN220U',score:'bad',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'confirmed',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-err',crop:'R'},
  's23-plus':{label:'S23+',year:2023,img:gi('samsung','samsung-galaxy-s23-plus-5g'),crop:'R',chip:'NXP SN220U',score:'bad',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-err',crop:'R'},
  's23':{label:'S23',year:2023,img:gi('samsung','samsung-galaxy-s23-5g'),crop:'R',chip:'NXP SN220U',score:'bad',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'confirmed',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-err',crop:'R'},
  's23-fe':{label:'S23 FE',year:2023,img:gi('samsung','samsung-galaxy-s23-fe'),crop:'R',chip:'NXP SN220U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'z-fold5':{label:'Z Fold5',year:2023,img:gi('samsung','samsung-galaxy-z-fold5'),crop:'R',chip:'NXP SN220U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'z-flip5':{label:'Z Flip5',year:2023,img:gi('samsung','samsung-galaxy-z-flip5'),crop:'R',chip:'NXP SN220U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'a54':{label:'Galaxy A54',year:2023,img:gi('samsung','samsung-galaxy-a54'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a34':{label:'Galaxy A34',year:2023,img:gi('samsung','samsung-galaxy-a34'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a14-5g':{label:'Galaxy A14 5G',year:2023,img:gi('samsung','samsung-galaxy-a14-5g'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'xcover6-pro':{label:'Xcover6 Pro',year:2023,img:gi('samsung','samsung-galaxy-xcover-6-pro'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's22-ultra':{label:'S22 Ultra',year:2022,img:gi('samsung','samsung-galaxy-s22-ultra-5g'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's22-plus':{label:'S22+',year:2022,img:gi('samsung','samsung-galaxy-s22-plus-5g'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's22':{label:'S22',year:2022,img:gi('samsung','samsung-galaxy-s22-5g'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'z-fold4':{label:'Z Fold4',year:2022,img:gi('samsung','samsung-galaxy-z-fold4'),crop:'R',chip:'NXP SN220U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'z-flip4':{label:'Z Flip4',year:2022,img:gi('samsung','samsung-galaxy-z-flip4'),crop:'R',chip:'NXP SN220U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'a53':{label:'Galaxy A53',year:2022,img:gi('samsung','samsung-galaxy-a53-5g'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a52-5g':{label:'Galaxy A52 5G',year:2022,img:gi('samsung','samsung-galaxy-a52-5g'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a33':{label:'Galaxy A33',year:2022,img:gi('samsung','samsung-galaxy-a33-5g'),crop:'R',chip:'NXP SN220U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's21-ultra':{label:'S21 Ultra',year:2021,img:gi('samsung','samsung-galaxy-s21-ultra-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's21-plus':{label:'S21+',year:2021,img:gi('samsung','samsung-galaxy-s21-plus-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's21':{label:'S21',year:2021,img:gi('samsung','samsung-galaxy-s21-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's21-fe':{label:'S21 FE',year:2021,img:gi('samsung','samsung-galaxy-s21-fe-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'z-fold3':{label:'Z Fold3',year:2021,img:gi('samsung','samsung-galaxy-z-fold3-5g'),crop:'R',chip:'NXP SN100U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'z-flip3':{label:'Z Flip3',year:2021,img:gi('samsung','samsung-galaxy-z-flip3-5g'),crop:'R',chip:'NXP SN100U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'a52':{label:'Galaxy A52',year:2021,img:gi('samsung','samsung-galaxy-a52'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a32':{label:'Galaxy A32',year:2021,img:gi('samsung','samsung-galaxy-a32'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a12':{label:'Galaxy A12',year:2021,img:gi('samsung','samsung-galaxy-a12'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'note20-ultra':{label:'Note 20 Ultra',year:2020,img:gi('samsung','samsung-galaxy-note20-ultra-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'note20':{label:'Note 20',year:2020,img:gi('samsung','samsung-galaxy-note20-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's20-ultra':{label:'S20 Ultra',year:2020,img:gi('samsung','samsung-galaxy-s20-ultra-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's20-plus':{label:'S20+',year:2020,img:gi('samsung','samsung-galaxy-s20-plus-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's20':{label:'S20',year:2020,img:gi('samsung','samsung-galaxy-s20-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's20-fe':{label:'S20 FE',year:2020,img:gi('samsung','samsung-galaxy-s20-fe-5g'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'z-fold2':{label:'Z Fold2',year:2020,img:gi('samsung','samsung-galaxy-z-fold-2-5g'),crop:'R',chip:'NXP SN100U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'z-flip':{label:'Z Flip',year:2020,img:gi('samsung','samsung-galaxy-z-flip'),crop:'R',chip:'NXP SN100U',score:'ko',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-warn',crop:'R'},
  'a51':{label:'Galaxy A51',year:2020,img:gi('samsung','samsung-galaxy-a51'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a71':{label:'Galaxy A71',year:2020,img:gi('samsung','samsung-galaxy-a71'),crop:'R',chip:'NXP SN100U',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's10-plus':{label:'S10+',year:2019,img:gi('samsung','samsung-galaxy-s10-plus'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's10':{label:'S10',year:2019,img:gi('samsung','samsung-galaxy-s10'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's10e':{label:'S10e',year:2019,img:gi('samsung','samsung-galaxy-s10e'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's10-5g':{label:'S10 5G',year:2019,img:gi('samsung','samsung-galaxy-s10-5g'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'note10-plus':{label:'Note 10+',year:2019,img:gi('samsung','samsung-galaxy-note10-plus-5g'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'note10':{label:'Note 10',year:2019,img:gi('samsung','samsung-galaxy-note10'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a50':{label:'Galaxy A50',year:2019,img:gi('samsung','samsung-galaxy-a50'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a70':{label:'Galaxy A70',year:2019,img:gi('samsung','samsung-galaxy-a70'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's9-plus':{label:'S9+',year:2018,img:gi('samsung','samsung-galaxy-s9-plus'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  's9':{label:'S9',year:2018,img:gi('samsung','samsung-galaxy-s9'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'note9':{label:'Note 9',year:2018,img:gi('samsung','samsung-galaxy-note9'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Centre dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.mid_back}],tap:'<b>Centre du dos</b>.',tapCls:'tb-ok',crop:'R'},
  'a8-2018':{label:'Galaxy A8 (2018)',year:2018,img:gi('samsung','samsung-galaxy-a8-2018'),crop:'R',chip:'NXP SN1xx',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers supérieur dos',size:'~55x40mm',conf:'estimated',src:'Samsung HK NFC',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok',crop:'R'},
}}
/* -- SONY -- */
sony:{label:'Sony',models:{
  'xp10-vii':{label:'Xperia 10 VII',year:2025,crop:'C',img:gi('sony','sony-xperia-10-vii-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp1-vii':{label:'Xperia 1 VII',year:2025,crop:'C',img:gi('sony','sony-xperia-1-vii-violet'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp1-vi':{label:'Xperia 1 VI',year:2024,crop:'C',img:gi('sony','sony-xperia-1-vi-red'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp10-vi':{label:'Xperia 10 VI',year:2024,crop:'C',img:gi('sony','sony-xperia-10-vi'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Centre dos',size:'~55x38mm',conf:'estimated',src:'Sony Support · logo N',ov:OV.mid_back}],tap:'<b>Centre du dos</b> — logo N visible.',tapCls:'tb-ok'},
  'xp5-v':{label:'Xperia 5 V',year:2023,crop:'C',img:gi('sony','sony-xperia-5-v-new'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp1-v':{label:'Xperia 1 V',year:2023,crop:'C',img:gi('sony','sony-xperia-1-v'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp10-v':{label:'Xperia 10 V',year:2023,crop:'C',img:gi('sony','sony-xperia-10-v-10'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Centre dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.mid_back}],tap:'<b>Centre du dos</b> — logo N visible.',tapCls:'tb-ok'},
  'xp5-iv':{label:'Xperia 5 IV',year:2022,crop:'C',img:gi('sony','sony-xperia-5-iv-ofic'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Centre dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.mid_back}],tap:'<b>Centre du dos</b> — logo N visible.',tapCls:'tb-ok'},
  'xp1-iv':{label:'Xperia 1 IV',year:2022,crop:'C',img:gi('sony','sony-xperia-1-iv-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp10-iv':{label:'Xperia 10 IV',year:2022,crop:'C',img:gi('sony','sony-xperia-10-iv'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Centre dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.mid_back}],tap:'<b>Centre du dos</b> — logo N visible.',tapCls:'tb-ok'},
  'xp-pro-i':{label:'Xperia Pro-I',year:2021,crop:'C',img:gi('sony','sony-xperia-pro-i'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp1-iii':{label:'Xperia 1 III',year:2021,crop:'C',img:gi('sony','sony-xperia-1-iii'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp5-iii':{label:'Xperia 5 III',year:2021,crop:'C',img:gi('sony','sony-xperia-5-iii'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp10-iii':{label:'Xperia 10 III',year:2021,crop:'C',img:gi('sony','sony-xperia-10-iii'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Centre dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.mid_back}],tap:'<b>Centre du dos</b> — logo N visible.',tapCls:'tb-ok'},
  'xp5-ii':{label:'Xperia 5 II',year:2020,crop:'C',img:gi('sony','sony-xperia-5-ii-5g-r'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp1-ii':{label:'Xperia 1 II',year:2020,crop:'C',img:gi('sony','sony-xperia-1-II-o'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp10-ii':{label:'Xperia 10 II',year:2020,crop:'C',img:gi('sony','sony-xperia-10-II-o'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Centre dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.mid_back}],tap:'<b>Centre du dos</b> — logo N visible.',tapCls:'tb-ok'},
  'xp-pro':{label:'Xperia Pro',year:2020,crop:'C',img:gi('sony','sony-xperia-pro-5g'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'estimated',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp5':{label:'Xperia 5',year:2019,crop:'C',img:gi('sony','sony-xperia-5-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp1':{label:'Xperia 1',year:2019,crop:'C',img:gi('sony','sony-xperia-1'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xp10-p':{label:'Xperia 10 Plus',year:2019,crop:'C',img:gi('sony','sony-xperia-10-plus-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Centre dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.mid_back}],tap:'<b>Centre du dos</b> — logo N visible.',tapCls:'tb-ok'},
  'xp10':{label:'Xperia 10',year:2019,crop:'C',img:gi('sony','sony-xperia-10-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Centre dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.mid_back}],tap:'<b>Centre du dos</b> — logo N visible.',tapCls:'tb-ok'},
  'xpxz3':{label:'Xperia XZ3',year:2018,crop:'C',img:gi('sony','sony-xperia-xz3-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxz2-p':{label:'Xperia XZ2 Premium',year:2018,crop:'C',img:gi('sony','sony-xperia-xz2-premium'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxz2':{label:'Xperia XZ2',year:2018,crop:'C',img:gi('sony','sony-xperia-xz2-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxz2c':{label:'Xperia XZ2 Compact',year:2018,crop:'C',img:gi('sony','sony-xperia-xz2-compact-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxa2-u':{label:'Xperia XA2 Ultra',year:2018,crop:'C',img:gi('sony','sony-xperia-xa2-ultra-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'estimated',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxa2':{label:'Xperia XA2',year:2018,crop:'C',img:gi('sony','sony-xperia-xa2-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'estimated',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxz1':{label:'Xperia XZ1',year:2017,crop:'C',img:gi('sony','sony-xperia-xz1-ofic'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxz1c':{label:'Xperia XZ1 Compact',year:2017,crop:'C',img:gi('sony','sony-xperia-xz1-compact'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxzs':{label:'Xperia XZs',year:2017,crop:'C',img:gi('sony','sony-xperia-xzs-2017'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxzprem':{label:'Xperia XZ Premium',year:2017,crop:'C',img:gi('sony','sony-xperia-xz-premium-2017'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxz':{label:'Xperia XZ',year:2016,crop:'C',img:gi('sony','sony-xperia-xz'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xpxp':{label:'Xperia X Performance',year:2016,crop:'C',img:gi('sony','sony-xperia-x-performance'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos (N)',pos:'Tiers sup. dos',size:'~55x38mm',conf:'confirmed',src:'Sony Support · logo N',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
}}
/* -- TCL -- */
tcl:{label:'TCL',models:{
  'tcl40r':{label:'TCL 40R 5G',year:2023,crop:'C',img:gi('tcl','tcl-40r-5g'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'tcl20pro':{label:'TCL 20 Pro 5G',year:2021,crop:'C',img:gi('tcl','tcl-20-pro-5g'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
}},

/* -- ULEFONE -- */
ulefone:{label:'Ulefone',models:{
  'armor24':{label:'Armor 24',year:2023,crop:'C',img:gi('ulefone','ulefone-armor-24'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'armor22':{label:'Armor 22',year:2023,crop:'C',img:gi('ulefone','ulefone-armor-22'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
}},

/* -- VIVO -- */
vivo:{label:'vivo',models:{
  'v-x200u':{label:'X200 Ultra',year:2025,crop:'C',img:gi('vivo','vivo-x200-ultra'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'v-x200p':{label:'X200 Pro',year:2024,crop:'C',img:gi('vivo','vivo-x200-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'v-x100p':{label:'X100 Pro',year:2024,crop:'C',img:gi('vivo','vivo-x100-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'v-v30p':{label:'V30 Pro',year:2024,crop:'C',img:gi('vivo','vivo-v30-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'v-x90p':{label:'X90 Pro',year:2023,crop:'C',img:gi('vivo','vivo-x90-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'v-v29':{label:'V29',year:2023,crop:'C',img:gi('vivo','vivo-v29'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'v-x80p':{label:'X80 Pro',year:2022,crop:'C',img:gi('vivo','vivo-x80-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'v-v25p':{label:'V25 Pro',year:2022,crop:'C',img:gi('vivo','vivo-v25-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
}},

/* -- XIAOMI -- */
xiaomi:{label:'Xiaomi',models:{
  'xi17u':{label:'Xiaomi 17 Ultra',year:2025,crop:'C',img:gi('xiaomi','xiaomi-17-ultra-global'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi17':{label:'Xiaomi 17',year:2025,crop:'C',img:gi('xiaomi','xiaomi-17'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi15su':{label:'Xiaomi 15S Pro',year:2025,crop:'C',img:gi('xiaomi','xiaomi-15s-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi15u':{label:'Xiaomi 15 Ultra',year:2025,crop:'C',img:gi('xiaomi','xiaomi-15-ultra-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi15':{label:'Xiaomi 15',year:2025,crop:'C',img:gi('xiaomi','xiaomi-15'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi15t-pro':{label:'Xiaomi 15T Pro',year:2025,crop:'C',img:gi('xiaomi','xiaomi-15t-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi15t':{label:'Xiaomi 15T',year:2025,crop:'C',img:gi('xiaomi','xiaomi-15t'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'pf8u':{label:'Poco F8 Ultra',year:2025,crop:'C',img:gi('xiaomi','xiaomi-poco-f8-ultra-'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'pf8pro':{label:'Poco F8 Pro',year:2025,crop:'C',img:gi('xiaomi','xiaomi-poco-f8-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'pf7u':{label:'Poco F7 Ultra',year:2025,crop:'C',img:gi('xiaomi','xiaomi-poco-f7-ultra'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn15pp':{label:'Redmi Note 15 Pro+',year:2025,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-15-pro-plus-global'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn15p':{label:'Redmi Note 15 Pro',year:2025,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-15-pro-global'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi14u':{label:'Xiaomi 14 Ultra',year:2024,crop:'C',img:gi('xiaomi','xiaomi-14-ultra'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi14t-pro':{label:'Xiaomi 14T Pro',year:2024,crop:'C',img:gi('xiaomi','xiaomi-14t-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi14t':{label:'Xiaomi 14T',year:2024,crop:'C',img:gi('xiaomi','xiaomi-14t'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi14':{label:'Xiaomi 14',year:2024,crop:'C',img:gi('xiaomi','xiaomi-14'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'pf6pro':{label:'Poco F6 Pro',year:2024,crop:'C',img:gi('xiaomi','xiaomi-poco-f6-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'px8pro':{label:'Poco X8 Pro',year:2024,crop:'C',img:gi('xiaomi','xiaomi-poco-x8-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn14pp':{label:'Redmi Note 14 Pro+',year:2024,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-14-pro-plus'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn14p':{label:'Redmi Note 14 Pro',year:2024,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-14-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi13u':{label:'Xiaomi 13 Ultra',year:2023,crop:'C',img:gi('xiaomi','xiaomi-13-ultra'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi13t-pro':{label:'Xiaomi 13T Pro',year:2023,crop:'C',img:gi('xiaomi','xiaomi-13t-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi13pro':{label:'Xiaomi 13 Pro',year:2023,crop:'C',img:gi('xiaomi','xiaomi-13-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi13':{label:'Xiaomi 13',year:2023,crop:'C',img:gi('xiaomi','xiaomi-13'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'pf5pro':{label:'Poco F5 Pro',year:2023,crop:'C',img:gi('xiaomi','xiaomi-poco-f5-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn13pp':{label:'Redmi Note 13 Pro+',year:2023,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-13-pro-plus'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn13p':{label:'Redmi Note 13 Pro',year:2023,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-13-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi12su':{label:'Xiaomi 12S Ultra',year:2022,crop:'C',img:gi('xiaomi','xiaomi-12s-ultra'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi12pro':{label:'Xiaomi 12 Pro',year:2022,crop:'C',img:gi('xiaomi','xiaomi-12-pro-5g'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi12t-pro':{label:'Xiaomi 12T Pro',year:2022,crop:'C',img:gi('xiaomi','xiaomi-12t-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi12t':{label:'Xiaomi 12T',year:2022,crop:'C',img:gi('xiaomi','xiaomi-12t'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi12':{label:'Xiaomi 12',year:2022,crop:'C',img:gi('xiaomi','xiaomi-12'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'pf4gt':{label:'Poco F4 GT',year:2022,crop:'C',img:gi('xiaomi','xiaomi-poco-f4-gt'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn12pp':{label:'Redmi Note 12 Pro+',year:2022,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-12-pro-plus'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi11u':{label:'Xiaomi 11 Ultra',year:2021,crop:'C',img:gi('xiaomi','xiaomi-mi-11-ultra'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi11t-pro':{label:'Xiaomi 11T Pro',year:2021,crop:'C',img:gi('xiaomi','xiaomi-11t-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi11':{label:'Xiaomi Mi 11',year:2021,crop:'C',img:gi('xiaomi','xiaomi-mi-11'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn11pro':{label:'Redmi Note 11 Pro',year:2021,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-11-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi10pro':{label:'Xiaomi Mi 10 Pro',year:2020,crop:'C',img:gi('xiaomi','xiaomi-mi-10-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi10t-pro':{label:'Xiaomi Mi 10T Pro',year:2020,crop:'C',img:gi('xiaomi','xiaomi-mi-10t-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi10':{label:'Xiaomi Mi 10',year:2020,crop:'C',img:gi('xiaomi','xiaomi-mi-10'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn10pro':{label:'Redmi Note 10 Pro',year:2020,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-10-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi9t-pro':{label:'Xiaomi Mi 9T Pro',year:2019,crop:'C',img:gi('xiaomi','xiaomi-mi-9t-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi9':{label:'Xiaomi Mi 9',year:2019,crop:'C',img:gi('xiaomi','xiaomi-mi-9'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'rn8pro':{label:'Redmi Note 8 Pro',year:2019,crop:'C',img:gi('xiaomi','xiaomi-redmi-note-8-pro'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'xi8':{label:'Xiaomi Mi 8',year:2018,crop:'C',img:gi('xiaomi','xiaomi-mi-8'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
  'pf1':{label:'Poco F1',year:2018,crop:'C',img:gi('xiaomi','xiaomi-poco-f1'),crop:'C',chip:'NXP (probable)',score:'ok',zones:1,range:'3-5 cm',dims:'N/A',ants:[{id:1,lbl:'Antenne dos',pos:'Tiers sup. dos',size:'~55x40mm',conf:'estimated',src:'Observations constructeur',ov:OV.top_back2}],tap:'<b>Tiers supérieur du dos</b>.',tapCls:'tb-ok'},
}},;
